SCREEN_WIDTH = 830  # WIDTH
SCREEN_HEIGHT = 620  # HEIGHT
SCREEN_TITLE = "BeanAHero - Beta Version"  # SCREEN_TITLE

PLAYER_HEIGHT = 33
PLAYER_WIDTH = 12



MOVEMENT_SPEED = 3

SPRITE_SCALING = 2

FACING_TOP = 0
FACING_RIGHT = 1
FACING_BOTTOM = 2
FACING_LEFT = 3
NOT_PRESSED = 99

ATTACK = 1
WAITING_ATTACK = 0

PICKING = 1
WAITING_PICKING = 0

UPDATES_PER_FRAME = 7
