# Window
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Animation Visualization"

MOVEMENT_SPEED = 5
MOVEMENT_SPEED_POWERUP = 7

SPRITE_SCALING = 2

FACING_TOP = 0
FACING_RIGHT = 1
FACING_BOTTOM = 2
FACING_LEFT = 3
NOT_PRESSED = 99

ATTACK = 1
WAITING_ATTACK = 0

PICKING = 1
WAITING_PICKING = 0

POWERUP_ENABLED = 1
POWERUP_DISABLED = 0

POWERUP_AVAILABLE_TIME = 10

UPDATES_PER_FRAME = 7